# Generated by Django 3.1.4 on 2022-02-28 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizor',
            new_name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
        migrations.AlterField(
            model_name='lead',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.agent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=True),
        ),
    ]
