# Generated by Django 3.1.4 on 2022-02-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20220228_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organizer',
            new_name='is_organizor',
        ),
    ]
