# Generated by Django 3.1.4 on 2022-03-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20220302_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
