# Generated by Django 3.1.4 on 2022-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20220302_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
